# -*- coding: utf-8 -*-
"""Laboratório9.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h9SBETnvHmheIPhtJq88s47au7Dojr_h
"""

print( 'Média Final\n')

 print('Notas de Laboratório\n')

NotaLab1 = float(input(f'\nPrimeira potuação:\n'))
NotaLab2 = float(input(f'\nSegunda pontuação:\n'))
NotaLab3 = float(input(f'\nTerceira pontuação:\n'))
NotaLab4 = float(input(f'\nQuarta pontuação:\n'))

calculo_peso = ((1*NotaLab1 + 2*NotaLab2 + 4*NotaLab3 + 5*NotaLab4)/12)


print('\nA Média Ponderada é:\n{:.1f}'.format(calculo_peso))

if (calculo_peso<= 2.5):
    
  print(f'\nNota Final = {calculo_peso:.2f}')


elif ((calculo_peso >= 2.6) and (media_ponderada <= 4.9)):
    
  exame = float(input('\nExame:\n'))

  NotaFinal_Exame = ((calculo_peso + exame)/2)

  print(f'\nA Nota Final é: {NotaFinal_Exame:.2f}'))
  
  if (NotaFinal_Exame <= 5.0):
    
    print('\nReprovado\n')
  
  else: 
    
    print('\nAprovado\n')
    
else: 
      
  print(f'\nNota Final = {calculo_peso:.2f}')



